// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPmFEEbjX9ha3LqSVIdgKcz2VDGzz81Xg',
    appId: '1:612281363431:android:4d1018977be69afdbfab42',
    messagingSenderId: '612281363431',
    projectId: 'auto-shopper-e8b9a',
    databaseURL: 'https://auto-shopper-e8b9a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auto-shopper-e8b9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFcKSH4oK9zS_es9dJejA24XsEBr79EoI',
    appId: '1:612281363431:ios:1a097bb7ddfbb490bfab42',
    messagingSenderId: '612281363431',
    projectId: 'auto-shopper-e8b9a',
    databaseURL: 'https://auto-shopper-e8b9a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auto-shopper-e8b9a.appspot.com',
    iosClientId: '612281363431-cj6set8goqhfq92enobe2tk7v8d3ra9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDraft1',
  );
}
